before_commands:
    - 'composer install --no-progress'
    - 'mkdir storage/'
    - 'touch storage/ot.db'
    - 'cli/config.php create'
    - 'cli/migration.php migrations:migrate --no-interaction'
filter:
    excluded_paths:
        - vendor/
        - bin/
        - config/
        - templates/
        - cli/
tools:
    php_mess_detector: true
    php_analyzer: true
    php_code_sniffer: true
    php_code_coverage: true
    php_cpd: true
    php_loc: true
    php_pdepend: true