before_commands:
    - composer install

tools:
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "silex/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["vendor","mock"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*", "silex/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["vendor","mock"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*","silex/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: [ "vendor","mock"]
    php_analyzer: true
    php_analyzer:
        filter:
            paths: ["src/*", "silex/*"]
    sensiolabs_security_checker: true