before_commands:
    - composer install --no-progress
    - mkdir storage
    - touch storage/ot.db
    - cli/config.php create
    - cli/migration.php migrations:migrate --no-interaction
    
tools:
    php_code_coverage:
        enabled: true
        #filter:
            #paths: ["src"]
    php_code_sniffer:
        enabled: true
        config:
            standard: ALL
        filter:
            paths: ["src/*", "tests/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["build/*", "tests", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*", "tests/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["build", "tests", "vendor"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["build", "tests", "vendor"]
    php_analyzer: true
    php_analyzer:
        filter:
            paths: ["src/*", "tests/*"]
    sensiolabs_security_checker: true
